# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
  end

  desc "Build the app"
  lane :beta do
    build_app
    hockey(
      api_token: "<hockey app api token>",
      release_type: '3',
      ipa: './build/PhotoWall.ipa'
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Register new device"
  lane :add_device do
    register_devices(
      devices: { '<device name>' => '<device identifier>' }
    )
  end
end
